<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <LangVersion>9</LangVersion>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../../src/WorldGen.Core/WorldGen.Core.csproj" />
  </ItemGroup>
</Project>
